import Curve from '@/components/Layout/Curve'
import Head from 'next/head'
import { motion } from 'framer-motion'
import Logo from "../../assets/3.jpeg";
import Image from 'next/image';

export default function About() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Curve >
        <h1>About</h1>
        <div className='body'>
            {/* <p> Nullam mattis mattis dictum. Praesent sit amet condimentum mi, quis venenatis lectus. Phasellus ac ante id purus viverra hendrerit quis at ex. Donec vitae augue pulvinar augue dictum fermentum dapibus nec tellus.</p>
            <p>Phasellus cursus, ante in eleifend vehicula, leo metus mattis est, sit amet dignissim dui nibh in dui. Nullam dictum tortor vitae quam condimentum, eget tincidunt nisi tincidunt. Praesent ut erat at purus gravida aliquam non a purus. Pellentesque sagittis in justo vel venenatis.</p> */}
         <motion.div
      id="about"
      initial="hidden"
      animate="visible"
      className="  flex flex-col items-center w-full justify-center"
    >

      <motion.div className="w-full max-w-6xl flex flex-col md:flex-row items-center justify-center   rounded-lg ">
        <motion.div className="flex flex-col items-center text-white w-full md:w-1/3  md:mb-0">
          {/* <motion.img
            src={Logo}
            alt="Profile Picture"
            className="rounded-lg w-32 object-cover h-32 md:w-[380px] md:h-[400px]"
            
          /> */}

          <Image
           src={Logo}
           alt="Profile Picture"
           className="rounded-lg w-32 object-cover h-32 md:w-[380px] md:h-[400px]"
          />
        </motion.div>
        
        <motion.div className="text-white w-full md:w-2/3 md:pl-8">
          <motion.p className="text-lg leading-relaxed mb-4">
            Hello! I am a dedicated software engineer with 1 year of experience in the industry. My expertise lies in web development, and I have a strong command over a wide array of technologies including HTML, CSS, JavaScript, React, React Native, Tailwind CSS, SQL, MySQL, PHP, MongoDB, Express.js, Node.js, Bootstrap, Framer Motion, and Next.js.
          </motion.p>
          <motion.p className="text-lg leading-relaxed mb-4">
            Throughout my career, I have contributed to numerous projects, with a notable one being a hotel booking application. In this project, I improved the functionality and added new features such as hotel and room list displays, hotel filtration, profile section, recent reservations area, GST details, booking cancellation, booking requests, and more.
          </motion.p>
          <motion.p className="text-lg leading-relaxed">
            I am passionate about coding and constantly strive to enhance my skills and stay updated with the latest industry trends. I am looking for exciting opportunities where I can leverage my skills to contribute to innovative projects and grow professionally.
          </motion.p>
        </motion.div>
      </motion.div>
    </motion.div>
        </div>
      </Curve>
    </>
  )
}
